/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_advancedvideo_rawdata_MediaPreProcessing */

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_io_agora_MusicPlayProcessing_start(JNIEnv *, jclass, jint mediaPlayerId);

JNIEXPORT void JNICALL Java_io_agora_MusicPlayProcessing_stop(JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_io_agora_MusicPlayProcessing_change(JNIEnv *, jclass, jint channelIndex);

#ifdef __cplusplus
}
#endif