-dontwarn androidx.viewbinding.**
-keep class androidx.viewbinding.** { *; }
-keep class * extends androidx.viewbinding.ViewBinding {*;}
-keep class * extends io.agora.baselibrary.base.BaseRecyclerViewAdapter$BaseViewHolder {*;}