# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
def commonPods
  use_frameworks!
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxRelay', '6.1.0'
  pod 'IGListKit', '~> 4.0.0'
  pod 'SwiftFormat/CLI'
  pod 'SDWebImage', '5.11.1'
#  pod 'AgoraLrcScore', :path => "AgoraLrcScoreView"
end

target 'Core' do
  commonPods
  use_frameworks!
end

target 'app' do
  commonPods
  use_frameworks!
#  pod 'AgoraRtcEngine_Special_iOS', '3.6.214'
  pod 'AgoraRtcEngine_iOS_Beta', '4.0.0-beta.1'
  pod 'AgoraLyricsScore', '~> 1.0.3'

end

target 'LrcView' do
  commonPods
  use_frameworks!
  pod 'Zip', '~> 2.1'
end

# target with leancloud sdk
target 'OnlineKTV_LeanCloud' do
  commonPods
  use_frameworks!
  pod 'LeanCloud'
end
